name: ci
on:
  push: {}
  repository_dispatch:
    types: [trigger_ci]
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14.0'
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go1.14.0-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v1
        with:
          path: .bindown
          key: bindown-${{ hashFiles('bindown.yml') }}
      - run: go mod download
      - run: script/generate --check
      - run: script/update-docs --check
      - run: script/test
      - run: script/lint
