name: releaser
on:
  - workflow_dispatch
jobs:
  tag:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: script/tag-release
        id: tagrelease
        env:
          GITHUB_TOKEN: ${{ github.token }}
    outputs:
      tag: ${{ steps.tagrelease.outputs.releasetag }}
  release:
    needs: tag
    if: ${{ needs.tag.outputs.tag != '' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14.0'
      - uses: actions/checkout@v2
        with:
          ref: v${{ needs.tag.outputs.tag }}
      - run: script/release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

