name: update-routes
on:
  schedule:
    - cron: '16 * * * *'
jobs:
  update-routes:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14.0'
      - run: script/new-schema-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
